routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MunaqosyahController;
use App\Http\Controllers\KomprehensifController;
use App\Http\Controllers\PenelitianController;
use App\Http\Controllers\ObservasiController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\PerpustakaanController;
use App\Http\Controllers\KunjunganController;

Auth::routes();

Route::get('/', [HomeController::class, 'index'])
->name('home');

Route::resources([
    'admin' => AdminController::class
]);

Route::resources([
    'mahasiswa' => MahasiswaController::class
]);

Route::resources([
    'munaqosyah' => MunaqosyahController::class
]);

Route::resources([
    'komprehensif' => KomprehensifController::class
]);

Route::resources([
    'penelitian' => PenelitianController::class
]);
Route::resources([
    'observasi' => ObservasiController::class
]);
Route::resources([
    'dosen' => DosenController::class
]);
Route::resources([
    'jurusan' => JurusanController::class
]);

Route::resources([
    'perpustakaan' => PerpustakaanController::class
]);
Route::resources([
    'kunjungan' => KunjunganController::class
]);

Route::get('/users/{user}/edit', [UserController::class,'edit'])
->middleware('can:update,user');

Route::patch('/users/{user}', [UserController::class,'update'])
->middleware('can:update,user');

Route::delete('/users/{user}', [UserController::class,'destroy'])
->middleware('can:delete,user');

resources/views/layouts/admin/breadcumb.blade.php
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="../">Beranda</a></li>
        <li><a href="../">Dummy</a></li>
        <li><a href="../">Dummy</a></li>
        <li class="is-active"><a href="#" aria-current="page">Beranda</a></li>
    </ul>
</nav>

resources/views/layouts/admin/header.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

resources/views/layouts/admin/navbar.blade.php
        <!-- START NAV -->
        <nav class="navbar is-transparent">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item brand-text" href="{{ route ('home')}}">
                        Sistem Informasi FAI
                    </a>
                    <div class="navbar-burger burger" data-target="navMenu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                {{-- <div id="navMenu" class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="admin.html">
                            Home
                        </a>
                        <a class="navbar-item" href="admin.html">
                            Orders
                        </a>
                        <a class="navbar-item" href="admin.html">
                            Payments
                        </a>
                        <a class="navbar-item" href="admin.html">
                            Exceptions
                        </a>
                        <a class="navbar-item" href="admin.html">
                            Reports
                        </a>
                    </div>
                </div> --}}
            </div>
        </nav>
        <!-- END NAV -->

resources/views/layouts/admin/sidebar.blade.php
<div class="column is-3 ">
    <aside class="menu is-hidden-mobile">
        <p class="menu-label">
            Umum
        </p>
        <ul class="menu-list">
            <li><a class="is-active">Dashboard</a></li>
        </ul>
        <p class="menu-label">
            Administrasi
        </p>
        <ul class="menu-list">
            <li>
                <a>Bank Data</a>
                <ul>
                    <li><a href="{{route('mahasiswa.index')}}">Mahasiswa</a></li>
                    <li><a href="#">Dosen</a></li>
                    <li><a href="{{route('jurusan.index')}}">Program Studi</a></li>
                    <li><a href="#">Mata Kuliah</a></li>
                </ul>
            </li>

            <li>
                <a>Surat Menyurat</a>
                <ul>
                    <li><a href="{{ route('munaqosyah.index')}}">Pendaftaran Munaqosah</a></li>
                    <li><a href="{{ route('penelitian.index')}}">Surat Izin Penelitian</a></li>
                    <li><a href="{{ route('observasi.index')}}">Surat Izin Observasi</a></li>
                    <li><a href="javascript:;">Surat Ujian Susulan</a></li>
                    <li><a href="javascript:;">Surat Keterangan Lulus</a></li>
                    <li><a href="javascript:;">Surat Bimbingan Skripsi</a></li>
                    <li><a href="javascript:;">Surat Izin Praktek</a></li>
                    <li><a href="{{ route('komprehensif.index')}}">Pendaftaran Komprehensif</a></li>
                </ul>
            </li>
        </ul>
        <p class="menu-label">
            Perpustakaan
        </p>
        <ul class="menu-list">
            <li><a href="{{ route('kunjungan.create')}}">Kunjungan (Front)</a></li>
            <li><a href="{{ route('kunjungan.index')}}">History Kunjungan</a></li>
        </ul>
    </aside>
</div>